const STORAGE_PRODUCTS='solarisgt_products_v1';
const STORAGE_ADMIN='solarisgt_admin_v1';
const STORAGE_CART='solarisgt_cart_v1';
const SUPABASE_CONFIG=window.SOLARIS_SUPABASE||{};
const supabaseClient=window.supabase?.createClient(SUPABASE_CONFIG.url,SUPABASE_CONFIG.publishableKey);
const DEMO_PRODUCTS=[
  {id:'demo-1',name:'Lámpara solar para jardín',category:'Lámparas solares',price:185,status:'Disponible',description:'Iluminación ambiental para senderos, patios y jardines.',image:'',demo:true},
  {id:'demo-2',name:'Aplique solar exterior',category:'Iluminación exterior',price:295,status:'Disponible',description:'Luz cálida para entradas, corredores y fachadas.',image:'',demo:true},
  {id:'demo-3',name:'Lámpara decorativa de mesa',category:'Decoración',price:240,status:'Por encargo',description:'Una pieza de luz suave para salas, dormitorios y rincones especiales.',image:'',demo:true},
  {id:'demo-4',name:'Guirnalda solar cálida',category:'Lámparas solares',price:160,status:'Disponible',description:'Ambiente acogedor para pérgolas, balcones y celebraciones.',image:'',demo:true},
  {id:'demo-5',name:'Lámpara colgante contemporánea',category:'Iluminación interior',price:475,status:'Por encargo',description:'Iluminación decorativa para comedor, cocina o recepción.',image:'',demo:true},
  {id:'demo-6',name:'Reflector solar compacto',category:'Iluminación exterior',price:325,status:'Disponible',description:'Luz práctica para áreas exteriores y accesos.',image:'',demo:true}
];
const ICONS={'Lámparas solares':'☀️','Iluminación exterior':'◉','Iluminación interior':'✦','Decoración':'◇'};
let products=loadProducts();let cart=loadCart();let currentCategory='Todos';
const $=id=>document.getElementById(id);
function loadProducts(){try{return JSON.parse(localStorage.getItem(STORAGE_PRODUCTS))||DEMO_PRODUCTS}catch{return DEMO_PRODUCTS}}
function loadCart(){try{return JSON.parse(localStorage.getItem(STORAGE_CART))||[]}catch{return []}}
function saveProducts(){localStorage.setItem(STORAGE_PRODUCTS,JSON.stringify(products));renderAll()}
async function loadRemoteProducts(){if(!supabaseClient)return;const{data,error}=await supabaseClient.from('products').select('*').order('created_at',{ascending:false});if(error){console.error('No se pudo cargar el catálogo',error);return}products=data.length?data.map(p=>({...p,image:p.image_url||'',demo:false})):DEMO_PRODUCTS;renderAll()}
function formatPrice(value){return new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',maximumFractionDigits:2}).format(value)}
function productCard(product){const image=product.image?`<img src="${escapeHtml(product.image)}" alt="${escapeHtml(product.name)}" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'placeholder-icon',textContent:'${ICONS[product.category]||'✦'}'}))">`:`<span class="placeholder-icon">${ICONS[product.category]||'✦'}</span>`;return `<article class="product-card"><div class="product-visual">${image}${product.demo?'<span class="demo-tag">DEMOSTRACIÓN</span>':''}</div><div class="product-body"><small>${escapeHtml(product.category)}</small><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.description)}</p><div class="product-bottom"><span class="product-price">${formatPrice(product.price)}</span><button class="mini-button" data-add="${product.id}">Comprar</button></div></div></article>`}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function renderAll(){renderFeatured();renderShop();renderAdminProducts();renderCart();$('productCount').textContent=`${products.length} producto${products.length===1?'':'s'}`}
function renderFeatured(){$('featuredGrid').innerHTML=products.slice(0,3).map(productCard).join('')}
function renderFilters(){const categories=['Todos',...new Set(products.map(p=>p.category))];$('categoryFilters').innerHTML=categories.map(c=>`<button class="filter ${c===currentCategory?'active':''}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{currentCategory=b.dataset.category;renderFilters();renderShop()})}
function renderShop(){const query=$('searchInput').value.trim().toLowerCase();const filtered=products.filter(p=>(currentCategory==='Todos'||p.category===currentCategory)&&(`${p.name} ${p.description}`.toLowerCase().includes(query)));$('shopGrid').innerHTML=filtered.map(productCard).join('');$('emptyState').hidden=filtered.length>0;renderFilters()}
function showRoute(){const route=location.hash.replace('#','')||'inicio';document.querySelectorAll('.view').forEach(v=>v.hidden=v.dataset.route!==route);document.querySelectorAll('#mainNav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${route}`));$('mainNav').classList.remove('open');$('menuButton').setAttribute('aria-expanded','false');if(route==='administrador')refreshAuth();window.scrollTo(0,0)}
$('menuButton').onclick=()=>{const open=$('mainNav').classList.toggle('open');$('menuButton').setAttribute('aria-expanded',String(open))};window.addEventListener('hashchange',showRoute);$('searchInput').addEventListener('input',renderShop);
async function hashPassword(password){if(globalThis.crypto?.subtle){const bytes=new TextEncoder().encode(password);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}let hash=2166136261;for(let i=0;i<password.length;i++){hash^=password.charCodeAt(i);hash=Math.imul(hash,16777619)}return `local-${(hash>>>0).toString(16)}`}
async function refreshAuth(){if(!supabaseClient){$('setupCard').hidden=true;$('loginCard').hidden=false;$('adminPanel').hidden=true;$('loginMessage').textContent='No se pudo conectar con Supabase.';return}const{data:{session}}=await supabaseClient.auth.getSession();const logged=session?.user?.email?.toLowerCase()===SUPABASE_CONFIG.adminEmail.toLowerCase();$('setupCard').hidden=true;$('loginCard').hidden=logged;$('adminPanel').hidden=!logged;if(logged)renderAll()}
$('setupForm').onsubmit=async e=>{e.preventDefault();const p=$('setupPassword').value;if(p!==$('setupConfirm').value){$('setupMessage').textContent='Las contraseñas no coinciden.';return}localStorage.setItem(STORAGE_ADMIN,await hashPassword(p));sessionStorage.setItem('solarisgt_logged','yes');e.target.reset();refreshAuth();toast('Acceso de administrador creado')};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMessage').textContent='Ingresando…';const{data,error}=await supabaseClient.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});const allowed=data.user?.email?.toLowerCase()===SUPABASE_CONFIG.adminEmail.toLowerCase();if(error||!allowed){if(data.session&&!allowed)await supabaseClient.auth.signOut();$('loginMessage').textContent='Correo o contraseña incorrectos.';return}$('loginMessage').textContent='';$('loginPassword').value='';await refreshAuth();toast('Sesión iniciada')};
$('logoutButton').onclick=async()=>{await supabaseClient.auth.signOut();await refreshAuth()};
$('changePasswordForm').onsubmit=async event=>{event.preventDefault();const current=$('currentPassword').value,newPassword=$('newPassword').value,confirmation=$('confirmNewPassword').value,message=$('changePasswordMessage');message.textContent='';if(newPassword!==confirmation){message.textContent='Las contraseñas nuevas no coinciden.';return}if(newPassword===current){message.textContent='La contraseña nueva debe ser diferente a la actual.';return}message.textContent='Verificando…';const{error:loginError}=await supabaseClient.auth.signInWithPassword({email:SUPABASE_CONFIG.adminEmail,password:current});if(loginError){message.textContent='La contraseña actual no es correcta.';return}const{error:updateError}=await supabaseClient.auth.updateUser({password:newPassword});if(updateError){message.textContent='No se pudo actualizar. Usa al menos 8 caracteres e inténtalo de nuevo.';return}event.target.reset();message.textContent='Contraseña actualizada correctamente.';toast('Contraseña actualizada')};
$('productForm').onsubmit=async e=>{e.preventDefault();const id=$('productId').value;const payload={name:$('productName').value.trim(),category:$('productCategory').value,price:Number($('productPrice').value),status:$('productStatus').value,description:$('productDescription').value.trim(),image_url:$('productImage').value.trim(),active:true};const isExisting=id&&!id.startsWith('demo-');const query=isExisting?supabaseClient.from('products').update(payload).eq('id',id):supabaseClient.from('products').insert(payload);const{error}=await query;if(error){toast('No se pudo guardar el producto');console.error(error);return}resetForm();await loadRemoteProducts();toast(isExisting?'Producto actualizado':'Producto agregado')};
function renderAdminProducts(){if(!$('adminProducts'))return;$('adminProducts').innerHTML=products.map(p=>`<article class="admin-item"><div><small>${escapeHtml(p.category)} · ${escapeHtml(p.status)}</small><h3>${escapeHtml(p.name)}</h3><p>${formatPrice(p.price)}${p.demo?' · Producto de demostración':''}</p></div><div class="admin-actions"><button class="icon-button" data-edit="${p.id}">Editar</button><button class="icon-button delete" data-delete="${p.id}">Eliminar</button></div></article>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete))}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('productId').value=p.id;$('productName').value=p.name;$('productCategory').value=p.category;$('productPrice').value=p.price;$('productStatus').value=p.status;$('productDescription').value=p.description;$('productImage').value=p.image;$('formTitle').textContent='Editar producto';$('cancelEdit').hidden=false;$('productName').focus()}
async function deleteProduct(id){const p=products.find(x=>x.id===id);if(!p||!confirm(`¿Eliminar “${p.name}”?`))return;if(id.startsWith('demo-')){products=products.filter(x=>x.id!==id);renderAll();toast('Demostración eliminada');return}const{error}=await supabaseClient.from('products').delete().eq('id',id);if(error){toast('No se pudo eliminar el producto');console.error(error);return}await loadRemoteProducts();toast('Producto eliminado')}
function resetForm(){$('productForm').reset();$('productId').value='';$('formTitle').textContent='Agregar producto';$('cancelEdit').hidden=true}$('cancelEdit').onclick=resetForm;
function saveCart(){localStorage.setItem(STORAGE_CART,JSON.stringify(cart));renderCart()}
function addToCart(id){const line=cart.find(item=>item.id===id);if(line)line.quantity+=1;else cart.push({id,quantity:1});saveCart();openCart();toast('Producto agregado al carrito')}
function changeCart(id,change){const line=cart.find(item=>item.id===id);if(!line)return;line.quantity+=change;if(line.quantity<=0)cart=cart.filter(item=>item.id!==id);saveCart()}
function removeFromCart(id){cart=cart.filter(item=>item.id!==id);saveCart()}
function cartDetails(){return cart.map(line=>({line,product:products.find(p=>p.id===line.id)})).filter(item=>item.product)}
function cartAmounts(){const subtotal=cartDetails().reduce((sum,item)=>sum+item.product.price*item.line.quantity,0);const shipping=subtotal>=800?0:35;return{subtotal,shipping,total:subtotal+shipping}}
function renderCart(){const details=cartDetails();const amounts=cartAmounts();$('cartCount').textContent=details.reduce((sum,item)=>sum+item.line.quantity,0);$('cartItems').innerHTML=details.map(({line,product})=>`<article class="cart-item"><div class="cart-item-icon">${ICONS[product.category]||'✦'}</div><div><b>${escapeHtml(product.name)}</b><small>${formatPrice(product.price)} c/u</small><div class="quantity"><button data-decrease="${product.id}" aria-label="Restar uno">−</button><span>${line.quantity}</span><button data-increase="${product.id}" aria-label="Sumar uno">+</button><button class="remove-line" data-remove="${product.id}">Eliminar</button></div></div><strong>${formatPrice(product.price*line.quantity)}</strong></article>`).join('');$('cartSubtotal').textContent=formatPrice(amounts.subtotal);$('cartShipping').textContent=amounts.shipping?formatPrice(amounts.shipping):'Gratis';$('cartTotal').textContent=formatPrice(amounts.total);$('shippingNotice').textContent=amounts.shipping?`Te faltan ${formatPrice(800-amounts.subtotal)} para obtener envío gratis.`:'¡Tu pedido tiene envío gratis!';$('shippingNotice').classList.toggle('free-shipping',!amounts.shipping);$('cartEmpty').hidden=details.length>0;$('cartCheckout').hidden=details.length===0}
function openCart(){$('cartDrawer').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');$('cartBackdrop').hidden=false;document.body.classList.add('cart-open')}
function closeCart(){$('cartDrawer').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true');$('cartBackdrop').hidden=true;document.body.classList.remove('cart-open')}
$('cartButton').onclick=openCart;$('closeCart').onclick=closeCart;$('cartBackdrop').onclick=closeCart;$('continueShopping').onclick=()=>{closeCart();location.hash='#tienda'};
document.addEventListener('click',event=>{const add=event.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const increase=event.target.closest('[data-increase]');if(increase)changeCart(increase.dataset.increase,1);const decrease=event.target.closest('[data-decrease]');if(decrease)changeCart(decrease.dataset.decrease,-1);const remove=event.target.closest('[data-remove]');if(remove)removeFromCart(remove.dataset.remove)});
function setupLocations(){const department=$('customerDepartment'),municipality=$('customerMunicipality'),locations=window.GUATEMALA_LOCATIONS||{};department.innerHTML='<option value="">Selecciona un departamento</option>'+Object.keys(locations).map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join('');department.onchange=()=>{const options=locations[department.value]||[];municipality.innerHTML=options.length?'<option value="">Selecciona un municipio</option>'+options.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join(''):'<option value="">Primero selecciona un departamento</option>';municipality.disabled=!options.length}}
setupLocations();
$('checkoutForm').onsubmit=async event=>{event.preventDefault();const details=cartDetails();if(!details.length)return;const data=new FormData(event.target);const amounts=cartAmounts();let orderId='';const databaseItems=details.filter(({product})=>/^[0-9a-f-]{36}$/i.test(product.id)).map(({line,product})=>({product_id:product.id,quantity:line.quantity}));if(databaseItems.length===details.length&&supabaseClient){const{data:savedId,error}=await supabaseClient.rpc('create_solaris_order',{customer_name:data.get('customerName'),customer_phone:data.get('customerPhone'),department:data.get('customerDepartment'),municipality:data.get('customerMunicipality'),address:data.get('customerAddress'),notes:data.get('customerNotes')||'',items:databaseItems});if(error){console.error('No se pudo registrar el pedido',error);toast('El pedido continuará por WhatsApp')}else orderId=savedId}const lines=details.map(({line,product})=>`• ${line.quantity} × ${product.name} — ${formatPrice(product.price*line.quantity)}`).join('\n');const message=[`Hola Solaris GT, deseo realizar este pedido:`,orderId?`Pedido: ${orderId}`:'',``,lines,``,`Productos: ${formatPrice(amounts.subtotal)}`,`Envío: ${amounts.shipping?formatPrice(amounts.shipping):'Gratis'}`,`Total estimado: ${formatPrice(amounts.total)}`,``,`Nombre: ${data.get('customerName')}`,`Teléfono: ${data.get('customerPhone')}`,`Departamento: ${data.get('customerDepartment')}`,`Municipio: ${data.get('customerMunicipality')}`,`Dirección: ${data.get('customerAddress')}`,data.get('customerNotes')?`Indicaciones: ${data.get('customerNotes')}`:''].filter(Boolean).join('\n');window.open(`https://wa.me/50252728320?text=${encodeURIComponent(message)}`,'_blank','noopener')};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function registerWebMCP(){const context=document.modelContext;if(!context?.registerTool)return;const categories=['Lámparas solares','Decoración','Iluminación interior','Iluminación exterior'];context.registerTool({name:'list_solaris_products',title:'Listar productos de Solaris GT',description:'Devuelve el catálogo actual de productos visible en la tienda.',inputSchema:{type:'object',properties:{category:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute({category}={}){return products.filter(p=>!category||p.category===category).map(({id,name,category:group,price,status})=>({id,name,category:group,price,status}))}});context.registerTool({name:'add_solaris_product',title:'Agregar producto a Solaris GT',description:'Agrega un producto al catálogo local y actualiza la tienda visible.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1},category:{type:'string',enum:categories},price:{type:'number',minimum:0},status:{type:'string',enum:['Disponible','Por encargo','Agotado']},description:{type:'string',minLength:1}},required:['name','category','price','description'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!input.name||!categories.includes(input.category)||!Number.isFinite(input.price)||input.price<0||!input.description)throw new Error('Datos de producto inválidos');const product={id:`product-${Date.now()}`,name:input.name.trim(),category:input.category,price:input.price,status:input.status||'Disponible',description:input.description.trim(),image:'',demo:false};products.unshift(product);saveProducts();return {success:true,id:product.id,name:product.name}}})}
$('year').textContent=new Date().getFullYear();renderAll();showRoute();registerWebMCP();loadRemoteProducts();
