const STORAGE_PRODUCTS='solarisgt_products_v1';
const STORAGE_ADMIN='solarisgt_admin_v1';
const STORAGE_CART='solarisgt_cart_v1';
const SUPABASE_CONFIG=window.SOLARIS_SUPABASE||{};
const supabaseClient=window.supabase?.createClient(SUPABASE_CONFIG.url,SUPABASE_CONFIG.publishableKey);
const PRODUCT_CATEGORIES=['Lámparas solares','Decoración','Iluminación interior','Iluminación exterior','Guirnaldas y ambiente','Reflectores solares','Accesorios','Otros'];
const DEMO_PRODUCTS=[
  {id:'demo-1',name:'Lámpara solar para jardín',category:'Lámparas solares',price:185,status:'Disponible',description:'Iluminación ambiental para senderos, patios y jardines.',image:'',demo:true},
  {id:'demo-2',name:'Aplique solar exterior',category:'Iluminación exterior',price:295,status:'Disponible',description:'Luz cálida para entradas, corredores y fachadas.',image:'',demo:true},
  {id:'demo-3',name:'Lámpara decorativa de mesa',category:'Decoración',price:240,status:'Por encargo',description:'Una pieza de luz suave para salas, dormitorios y rincones especiales.',image:'',demo:true},
  {id:'demo-4',name:'Guirnalda solar cálida',category:'Lámparas solares',price:160,status:'Disponible',description:'Ambiente acogedor para pérgolas, balcones y celebraciones.',image:'',demo:true},
  {id:'demo-5',name:'Lámpara colgante contemporánea',category:'Iluminación interior',price:475,status:'Por encargo',description:'Iluminación decorativa para comedor, cocina o recepción.',image:'',demo:true},
  {id:'demo-6',name:'Reflector solar compacto',category:'Iluminación exterior',price:325,status:'Disponible',description:'Luz práctica para áreas exteriores y accesos.',image:'',demo:true}
];
const ICONS={'Lámparas solares':'☀️','Iluminación exterior':'◉','Iluminación interior':'✦','Decoración':'◇','Guirnaldas y ambiente':'✧','Reflectores solares':'☼','Accesorios':'＋','Otros':'◆'};
let products=loadProducts();let cart=loadCart();let currentCategory='Todos';
let customerAuthMode='login';
let pendingImageFiles=[];let editingImages=[];const galleryPositions={};
const $=id=>document.getElementById(id);
function loadProducts(){try{return JSON.parse(localStorage.getItem(STORAGE_PRODUCTS))||DEMO_PRODUCTS}catch{return DEMO_PRODUCTS}}
function loadCart(){try{return JSON.parse(localStorage.getItem(STORAGE_CART))||[]}catch{return []}}
function saveProducts(){localStorage.setItem(STORAGE_PRODUCTS,JSON.stringify(products));renderAll()}
async function loadRemoteProducts(){if(!supabaseClient)return;const{data,error}=await supabaseClient.from('products').select('*').order('created_at',{ascending:false});if(error){console.error('No se pudo cargar el catálogo',error);return}products=data.length?data.map(p=>{const images=Array.isArray(p.image_urls)?p.image_urls.filter(Boolean):[];if(p.image_url&&!images.includes(p.image_url))images.unshift(p.image_url);return({...p,image:images[0]||p.image_url||'',images,brand:p.brand||'',model:p.model||'',old_price:p.old_price||null,label:p.label||'',warranty:p.warranty||'',demo:false})}):DEMO_PRODUCTS;renderAll()}
function formatPrice(value){return new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',maximumFractionDigits:2}).format(value)}
function productImages(product){const images=Array.isArray(product.images)?product.images.filter(Boolean):[];if(product.image&&!images.includes(product.image))images.unshift(product.image);return images}
function productCard(product){const images=productImages(product),position=Math.min(galleryPositions[product.id]||0,Math.max(0,images.length-1)),current=images[position];const image=current?`<img src="${escapeHtml(current)}" alt="${escapeHtml(product.name)} — imagen ${position+1}" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'placeholder-icon',textContent:'${ICONS[product.category]||'✦'}'}))">`:`<span class="placeholder-icon">${ICONS[product.category]||'✦'}</span>`;const gallery=images.length>1?`<button class="gallery-button prev" type="button" data-gallery="${product.id}" data-step="-1" aria-label="Imagen anterior">‹</button><button class="gallery-button next" type="button" data-gallery="${product.id}" data-step="1" aria-label="Imagen siguiente">›</button><span class="gallery-count">${position+1}/${images.length}</span>`:'';const label=product.label?`<span class="product-label">${escapeHtml(product.label)}</span>`:'';const brand=[product.brand,product.model].filter(Boolean).join(' · ');const oldPrice=product.old_price&&Number(product.old_price)>Number(product.price)?`<del>${formatPrice(product.old_price)}</del>`:'';return `<article class="product-card"><div class="product-visual">${image}${gallery}${label}${product.demo?'<span class="demo-tag">DEMOSTRACIÓN</span>':''}</div><div class="product-body"><small>${escapeHtml(product.category)}</small><h3>${escapeHtml(product.name)}</h3>${brand?`<span class="product-brand">${escapeHtml(brand)}</span>`:''}<p>${escapeHtml(product.description)}</p><div class="product-meta"><span>${escapeHtml(product.status||'Consultar')}</span>${product.warranty?`<span>Garantía: ${escapeHtml(product.warranty)}</span>`:''}</div><div class="product-bottom"><span class="product-price">${oldPrice}${formatPrice(product.price)}</span><button class="mini-button" data-add="${product.id}" ${product.status==='Agotado'?'disabled':''}>${product.status==='Agotado'?'Agotado':'Comprar'}</button></div></div></article>`}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function renderAll(){renderFeatured();renderShop();renderAdminProducts();renderCart();$('productCount').textContent=`${products.length} producto${products.length===1?'':'s'}`}
function renderFeatured(){$('featuredGrid').innerHTML=products.slice(0,3).map(productCard).join('')}
function renderFilters(){const categories=['Todos',...new Set(products.map(p=>p.category))];$('categoryFilters').innerHTML=categories.map(c=>`<button class="filter ${c===currentCategory?'active':''}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{currentCategory=b.dataset.category;renderFilters();renderShop()})}
function renderShop(){const query=$('searchInput').value.trim().toLowerCase();let filtered=products.filter(p=>(currentCategory==='Todos'||p.category===currentCategory)&&(`${p.name} ${p.description} ${p.brand||''} ${p.model||''}`.toLowerCase().includes(query)));const sort=$('sortSelect').value;if(sort==='price-asc')filtered.sort((a,b)=>a.price-b.price);if(sort==='price-desc')filtered.sort((a,b)=>b.price-a.price);if(sort==='name')filtered.sort((a,b)=>a.name.localeCompare(b.name,'es'));$('shopGrid').innerHTML=filtered.map(productCard).join('');$('resultsCount').textContent=`${filtered.length} producto${filtered.length===1?'':'s'} encontrado${filtered.length===1?'':'s'}`;$('emptyState').hidden=filtered.length>0;renderFilters()}
function showRoute(){const route=location.hash.replace('#','')||'inicio';document.querySelectorAll('.view').forEach(v=>v.hidden=v.dataset.route!==route);document.querySelectorAll('#mainNav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${route}`));$('mainNav').classList.remove('open');$('menuButton').setAttribute('aria-expanded','false');if(route==='administrador')refreshAuth();if(route==='cuenta')refreshCustomerAuth();window.scrollTo(0,0)}
$('menuButton').onclick=()=>{const open=$('mainNav').classList.toggle('open');$('menuButton').setAttribute('aria-expanded',String(open))};window.addEventListener('hashchange',showRoute);$('searchInput').addEventListener('input',renderShop);$('sortSelect').addEventListener('change',renderShop);
async function hashPassword(password){if(globalThis.crypto?.subtle){const bytes=new TextEncoder().encode(password);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}let hash=2166136261;for(let i=0;i<password.length;i++){hash^=password.charCodeAt(i);hash=Math.imul(hash,16777619)}return `local-${(hash>>>0).toString(16)}`}
function setCustomerAuthMode(mode){customerAuthMode=mode;document.querySelectorAll('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('customerNameField').hidden=mode!=='signup';$('customerAccountName').required=mode==='signup';$('customerAuthTitle').textContent=mode==='signup'?'Crear cuenta':'Iniciar sesión';$('customerAuthSubmit').textContent=mode==='signup'?'Crear cuenta':'Ingresar';$('customerAccountPassword').autocomplete=mode==='signup'?'new-password':'current-password';$('customerAuthMessage').textContent=''}
async function signInWithProvider(provider){const message=$('customerAuthMessage');message.textContent=`Abriendo ${provider==='google'?'Google':'Facebook'}…`;sessionStorage.setItem('solaris_oauth_pending','yes');const redirectTo=`${location.origin}${location.pathname}`;const{error}=await supabaseClient.auth.signInWithOAuth({provider,options:{redirectTo}});if(error){sessionStorage.removeItem('solaris_oauth_pending');message.textContent=`No se pudo iniciar con ${provider==='google'?'Google':'Facebook'}. Verifica que el proveedor esté activado en Supabase.`}}
async function refreshCustomerAuth(){if(!supabaseClient){$('customerAuthLoading').hidden=true;$('customerLoggedOut').hidden=false;$('customerAuthMessage').textContent='No se pudo conectar con el servicio de cuentas.';return}const{data:{session}}=await supabaseClient.auth.getSession();$('customerAuthLoading').hidden=true;$('customerLoggedOut').hidden=Boolean(session);$('customerLoggedIn').hidden=!session;if(session){const user=session.user;const name=user.user_metadata?.full_name||user.email?.split('@')[0]||'Cliente';$('customerDisplayName').textContent=`Hola, ${name}`;$('customerDisplayEmail').textContent=user.email||'';$('customerInitial').textContent=name.charAt(0).toUpperCase()}}
document.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>setCustomerAuthMode(button.dataset.authMode));
document.querySelectorAll('[data-oauth]').forEach(button=>button.onclick=()=>signInWithProvider(button.dataset.oauth));
$('customerAuthForm').onsubmit=async event=>{event.preventDefault();const email=$('customerAccountEmail').value.trim(),password=$('customerAccountPassword').value,message=$('customerAuthMessage');message.textContent=customerAuthMode==='signup'?'Creando tu cuenta…':'Ingresando…';if(customerAuthMode==='signup'){const fullName=$('customerAccountName').value.trim();const{data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:fullName}}});if(error){message.textContent=error.message.includes('already')?'Ese correo ya tiene una cuenta.':'No se pudo crear la cuenta. Revisa los datos.';return}message.textContent=data.session?'Cuenta creada correctamente.':'Cuenta creada. Revisa tu correo para confirmarla.';if(data.session)await refreshCustomerAuth();return}const{error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){message.textContent='Correo o contraseña incorrectos.';return}event.target.reset();await refreshCustomerAuth();toast('Sesión iniciada')};
$('resetPasswordButton').onclick=async()=>{const email=$('customerAccountEmail').value.trim();if(!email){$('customerAuthMessage').textContent='Escribe primero tu correo electrónico.';return}const redirectTo=`${location.origin}${location.pathname}#cuenta`;const{error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo});$('customerAuthMessage').textContent=error?'No se pudo enviar el enlace. Inténtalo nuevamente.':'Te enviamos un enlace para recuperar tu contraseña.'};
$('customerLogoutButton').onclick=async()=>{await supabaseClient.auth.signOut();await refreshCustomerAuth();toast('Sesión cerrada')};
async function refreshAuth(){if(!supabaseClient){$('setupCard').hidden=true;$('loginCard').hidden=false;$('adminPanel').hidden=true;$('loginMessage').textContent='No se pudo conectar con Supabase.';return}const{data:{session}}=await supabaseClient.auth.getSession();const logged=session?.user?.email?.toLowerCase()===SUPABASE_CONFIG.adminEmail.toLowerCase();$('setupCard').hidden=true;$('loginCard').hidden=logged;$('adminPanel').hidden=!logged;if(logged)renderAll()}
$('setupForm').onsubmit=async e=>{e.preventDefault();const p=$('setupPassword').value;if(p!==$('setupConfirm').value){$('setupMessage').textContent='Las contraseñas no coinciden.';return}localStorage.setItem(STORAGE_ADMIN,await hashPassword(p));sessionStorage.setItem('solarisgt_logged','yes');e.target.reset();refreshAuth();toast('Acceso de administrador creado')};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMessage').textContent='Ingresando…';const{data,error}=await supabaseClient.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});const allowed=data.user?.email?.toLowerCase()===SUPABASE_CONFIG.adminEmail.toLowerCase();if(error||!allowed){if(data.session&&!allowed)await supabaseClient.auth.signOut();$('loginMessage').textContent='Correo o contraseña incorrectos.';return}$('loginMessage').textContent='';$('loginPassword').value='';await refreshAuth();toast('Sesión iniciada')};
$('logoutButton').onclick=async()=>{await supabaseClient.auth.signOut();await refreshAuth()};
$('changePasswordForm').onsubmit=async event=>{event.preventDefault();const current=$('currentPassword').value,newPassword=$('newPassword').value,confirmation=$('confirmNewPassword').value,message=$('changePasswordMessage');message.textContent='';if(newPassword!==confirmation){message.textContent='Las contraseñas nuevas no coinciden.';return}if(newPassword===current){message.textContent='La contraseña nueva debe ser diferente a la actual.';return}message.textContent='Verificando…';const{error:loginError}=await supabaseClient.auth.signInWithPassword({email:SUPABASE_CONFIG.adminEmail,password:current});if(loginError){message.textContent='La contraseña actual no es correcta.';return}const{error:updateError}=await supabaseClient.auth.updateUser({password:newPassword});if(updateError){message.textContent='No se pudo actualizar. Usa al menos 8 caracteres e inténtalo de nuevo.';return}event.target.reset();message.textContent='Contraseña actualizada correctamente.';toast('Contraseña actualizada')};
function renderImagePreview(){const preview=$('productImagePreview');const existing=editingImages.map((url,index)=>`<div class="preview-image"><img src="${escapeHtml(url)}" alt="Imagen guardada ${index+1}"><button type="button" data-remove-existing="${index}" aria-label="Quitar imagen">×</button></div>`);const pending=pendingImageFiles.map((file,index)=>`<div class="preview-image"><img src="${URL.createObjectURL(file)}" alt="Imagen nueva ${index+1}"><button type="button" data-remove-pending="${index}" aria-label="Quitar imagen">×</button></div>`);preview.innerHTML=[...existing,...pending].join('')||'<span>Las imágenes seleccionadas aparecerán aquí.</span>'}
$('productImageFile').addEventListener('change',event=>{const incoming=Array.from(event.target.files||[]);if(incoming.some(file=>file.size>5242880)){toast('Cada imagen debe pesar menos de 5 MB');event.target.value='';return}pendingImageFiles=[...pendingImageFiles,...incoming].slice(0,10);event.target.value='';renderImagePreview()});
$('productImagePreview').addEventListener('click',event=>{const existing=event.target.closest('[data-remove-existing]'),pending=event.target.closest('[data-remove-pending]');if(existing){editingImages.splice(Number(existing.dataset.removeExisting),1);renderImagePreview()}if(pending){pendingImageFiles.splice(Number(pending.dataset.removePending),1);renderImagePreview()}});
$('productForm').onsubmit=async e=>{e.preventDefault();const id=$('productId').value;let images=[...editingImages];const manualUrl=$('productImage').value.trim();if(manualUrl&&!images.includes(manualUrl))images.push(manualUrl);if(pendingImageFiles.length){toast(`Subiendo ${pendingImageFiles.length} imagen${pendingImageFiles.length===1?'':'es'}…`);for(const file of pendingImageFiles){const extension=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${crypto.randomUUID()}.${extension}`;const{error:uploadError}=await supabaseClient.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false});if(uploadError){toast('No se pudieron subir todas las imágenes');console.error(uploadError);return}images.push(supabaseClient.storage.from('product-images').getPublicUrl(path).data.publicUrl)}}images=[...new Set(images)].slice(0,10);const oldPrice=$('productOldPrice').value;const payload={name:$('productName').value.trim(),brand:$('productBrand').value.trim(),model:$('productModel').value.trim(),category:$('productCategory').value,old_price:oldPrice?Number(oldPrice):null,price:Number($('productPrice').value),label:$('productLabel').value,status:$('productStatus').value,warranty:$('productWarranty').value,description:$('productDescription').value.trim(),image_url:images[0]||'',image_urls:images,active:true};const isExisting=id&&!id.startsWith('demo-');const query=isExisting?supabaseClient.from('products').update(payload).eq('id',id):supabaseClient.from('products').insert(payload);const{error}=await query;if(error){toast('No se pudo guardar. Ejecuta la migración de imágenes en Supabase.');console.error(error);return}resetForm();await loadRemoteProducts();toast(isExisting?'Producto actualizado':'Producto agregado')};
function renderAdminProducts(){if(!$('adminProducts'))return;$('adminProducts').innerHTML=products.map(p=>`<article class="admin-item"><div><small>${escapeHtml(p.category)} · ${escapeHtml(p.status)}</small><h3>${escapeHtml(p.name)}</h3><p>${formatPrice(p.price)}${p.demo?' · Producto de demostración':''}</p></div><div class="admin-actions"><button class="icon-button" data-edit="${p.id}">Editar</button><button class="icon-button delete" data-delete="${p.id}">Eliminar</button></div></article>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete))}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('productId').value=p.id;$('productName').value=p.name;$('productBrand').value=p.brand||'';$('productModel').value=p.model||'';$('productCategory').value=PRODUCT_CATEGORIES.includes(p.category)?p.category:'Otros';$('productOldPrice').value=p.old_price||'';$('productPrice').value=p.price;$('productLabel').value=p.label||'';$('productStatus').value=p.status;$('productWarranty').value=p.warranty||'Consultar';$('productDescription').value=p.description;$('productImage').value='';editingImages=productImages(p);pendingImageFiles=[];renderImagePreview();$('formTitle').textContent='Editar producto';$('cancelEdit').hidden=false;$('productName').focus()}
async function deleteProduct(id){const p=products.find(x=>x.id===id);if(!p||!confirm(`¿Eliminar “${p.name}”?`))return;if(id.startsWith('demo-')){products=products.filter(x=>x.id!==id);renderAll();toast('Demostración eliminada');return}const{error}=await supabaseClient.from('products').delete().eq('id',id);if(error){toast('No se pudo eliminar el producto');console.error(error);return}await loadRemoteProducts();toast('Producto eliminado')}
function resetForm(){$('productForm').reset();$('productId').value='';pendingImageFiles=[];editingImages=[];renderImagePreview();$('formTitle').textContent='Agregar producto';$('cancelEdit').hidden=true}$('cancelEdit').onclick=resetForm;
function saveCart(){localStorage.setItem(STORAGE_CART,JSON.stringify(cart));renderCart()}
function addToCart(id){const line=cart.find(item=>item.id===id);if(line)line.quantity+=1;else cart.push({id,quantity:1});saveCart();openCart();toast('Producto agregado al carrito')}
function changeCart(id,change){const line=cart.find(item=>item.id===id);if(!line)return;line.quantity+=change;if(line.quantity<=0)cart=cart.filter(item=>item.id!==id);saveCart()}
function removeFromCart(id){cart=cart.filter(item=>item.id!==id);saveCart()}
function cartDetails(){return cart.map(line=>({line,product:products.find(p=>p.id===line.id)})).filter(item=>item.product)}
function cartAmounts(){const subtotal=cartDetails().reduce((sum,item)=>sum+item.product.price*item.line.quantity,0);const shipping=subtotal>=800?0:35;return{subtotal,shipping,total:subtotal+shipping}}
function renderCart(){const details=cartDetails();const amounts=cartAmounts();$('cartCount').textContent=details.reduce((sum,item)=>sum+item.line.quantity,0);$('cartItems').innerHTML=details.map(({line,product})=>`<article class="cart-item"><div class="cart-item-icon">${ICONS[product.category]||'✦'}</div><div><b>${escapeHtml(product.name)}</b><small>${formatPrice(product.price)} c/u</small><div class="quantity"><button data-decrease="${product.id}" aria-label="Restar uno">−</button><span>${line.quantity}</span><button data-increase="${product.id}" aria-label="Sumar uno">+</button><button class="remove-line" data-remove="${product.id}">Eliminar</button></div></div><strong>${formatPrice(product.price*line.quantity)}</strong></article>`).join('');$('cartSubtotal').textContent=formatPrice(amounts.subtotal);$('cartShipping').textContent=amounts.shipping?formatPrice(amounts.shipping):'Gratis';$('cartTotal').textContent=formatPrice(amounts.total);$('shippingNotice').textContent=amounts.shipping?`Te faltan ${formatPrice(800-amounts.subtotal)} para obtener envío gratis.`:'¡Tu pedido tiene envío gratis!';$('shippingNotice').classList.toggle('free-shipping',!amounts.shipping);$('cartEmpty').hidden=details.length>0;$('cartCheckout').hidden=details.length===0}
function openCart(){$('cartDrawer').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');$('cartBackdrop').hidden=false;document.body.classList.add('cart-open')}
function closeCart(){$('cartDrawer').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true');$('cartBackdrop').hidden=true;document.body.classList.remove('cart-open')}
$('cartButton').onclick=openCart;$('closeCart').onclick=closeCart;$('cartBackdrop').onclick=closeCart;$('continueShopping').onclick=()=>{closeCart();location.hash='#tienda'};
document.addEventListener('click',event=>{const gallery=event.target.closest('[data-gallery]');if(gallery){const product=products.find(item=>String(item.id)===gallery.dataset.gallery),images=product?productImages(product):[];if(images.length){const current=galleryPositions[product.id]||0;galleryPositions[product.id]=(current+Number(gallery.dataset.step)+images.length)%images.length;renderFeatured();renderShop()}return}const add=event.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const increase=event.target.closest('[data-increase]');if(increase)changeCart(increase.dataset.increase,1);const decrease=event.target.closest('[data-decrease]');if(decrease)changeCart(decrease.dataset.decrease,-1);const remove=event.target.closest('[data-remove]');if(remove)removeFromCart(remove.dataset.remove)});
function setupLocations(){const department=$('customerDepartment'),municipality=$('customerMunicipality'),locations=window.GUATEMALA_LOCATIONS||{};department.innerHTML='<option value="">Selecciona un departamento</option>'+Object.keys(locations).map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join('');department.onchange=()=>{const options=locations[department.value]||[];municipality.innerHTML=options.length?'<option value="">Selecciona un municipio</option>'+options.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join(''):'<option value="">Primero selecciona un departamento</option>';municipality.disabled=!options.length}}
setupLocations();
$('checkoutForm').onsubmit=async event=>{event.preventDefault();const details=cartDetails();if(!details.length)return;const data=new FormData(event.target);const amounts=cartAmounts();let orderId='';const databaseItems=details.filter(({product})=>/^[0-9a-f-]{36}$/i.test(product.id)).map(({line,product})=>({product_id:product.id,quantity:line.quantity}));if(databaseItems.length===details.length&&supabaseClient){const{data:savedId,error}=await supabaseClient.rpc('create_solaris_order',{customer_name:data.get('customerName'),customer_phone:data.get('customerPhone'),department:data.get('customerDepartment'),municipality:data.get('customerMunicipality'),address:data.get('customerAddress'),notes:data.get('customerNotes')||'',items:databaseItems});if(error){console.error('No se pudo registrar el pedido',error);toast('El pedido continuará por WhatsApp')}else orderId=savedId}const lines=details.map(({line,product})=>`• ${line.quantity} × ${product.name} — ${formatPrice(product.price*line.quantity)}`).join('\n');const message=[`Hola Solaris GT, deseo realizar este pedido:`,orderId?`Pedido: ${orderId}`:'',``,lines,``,`Productos: ${formatPrice(amounts.subtotal)}`,`Envío: ${amounts.shipping?formatPrice(amounts.shipping):'Gratis'}`,`Total estimado: ${formatPrice(amounts.total)}`,``,`Nombre: ${data.get('customerName')}`,`Teléfono: ${data.get('customerPhone')}`,`Departamento: ${data.get('customerDepartment')}`,`Municipio: ${data.get('customerMunicipality')}`,`Dirección: ${data.get('customerAddress')}`,data.get('customerNotes')?`Indicaciones: ${data.get('customerNotes')}`:''].filter(Boolean).join('\n');window.open(`https://wa.me/50252728320?text=${encodeURIComponent(message)}`,'_blank','noopener')};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function registerWebMCP(){const context=document.modelContext;if(!context?.registerTool)return;context.registerTool({name:'list_solaris_products',title:'Listar productos de Solaris GT',description:'Devuelve el catálogo actual de productos visible en la tienda.',inputSchema:{type:'object',properties:{category:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute({category}={}){return products.filter(p=>!category||p.category===category).map(({id,name,category:group,price,status})=>({id,name,category:group,price,status}))}});context.registerTool({name:'add_solaris_product',title:'Agregar producto a Solaris GT',description:'Agrega un producto al catálogo local y actualiza la tienda visible.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1},category:{type:'string',enum:PRODUCT_CATEGORIES},price:{type:'number',minimum:0},status:{type:'string'},description:{type:'string',minLength:1}},required:['name','category','price','description'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!input.name||!PRODUCT_CATEGORIES.includes(input.category)||!Number.isFinite(input.price)||input.price<0||!input.description)throw new Error('Datos de producto inválidos');const product={id:`product-${Date.now()}`,name:input.name.trim(),category:input.category,price:input.price,status:input.status||'Disponible',description:input.description.trim(),image:'',demo:false};products.unshift(product);saveProducts();return {success:true,id:product.id,name:product.name}}})}
if(supabaseClient)supabaseClient.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN'&&sessionStorage.getItem('solaris_oauth_pending')==='yes'){sessionStorage.removeItem('solaris_oauth_pending');location.hash='#cuenta'}if(location.hash==='#cuenta')setTimeout(refreshCustomerAuth,0);if(location.hash==='#administrador')setTimeout(refreshAuth,0)});
$('year').textContent=new Date().getFullYear();setCustomerAuthMode('login');renderImagePreview();renderAll();showRoute();registerWebMCP();loadRemoteProducts();
